name: spring-kafka-reply
server:
  port: 9090

logging:
  config: classpath:logback-async.xml
spring:
  # 数据库连接配置
  datasource:
    driverClassName: org.h2.Driver
    username: user
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  # kafka配置
  kafka:
    bootstrapServers: 47.101.155.205:9092
    consumer:
      group-id: spring-kafka
      auto-offset-reset: earliest
    admin:
      fail-fast: true