name: spring-kafka
server:
#  address: 127.0.0.1
  port: 8080

logging:
  config: classpath:logback-async.xml

spring:
  kafka:
    bootstrapServers: 47.101.155.205:9092
    consumer:
      group-id: spring-kafka
      auto-offset-reset: earliest