name: @name@ yaml
spring:
  profiles:
    active: dev
acme:
  remoteAddress: 127.0.0.1
  security:
    - username: oycm1
      password: oycm1
    - username: oycm2
      password: oycm2
---
spring:
  profiles: dev
server:
  address: 127.0.0.1
  port: 80