CREATE TABLE CUSTOMER
(
    ID                INT PRIMARY KEY,
    FIRST_NAME        VARCHAR(50) NOT NULL,
    LAST_NAME         VARCHAR(50) NOT NULL,
    EMAIL             VARCHAR(100) UNIQUE,
    AGE               INT CHECK (AGE >= 18),
    REGISTRATION_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);